### ISSUE TITLE
MacOS target support?

### ISSUE THREAD

**Issue by DeltriDev** [swiftlang/swift-sdk-generator#111]
Hello! Found out this project while trying to find a way to build from my Linux/windows machine to Mac. It seems like windows host support is planned and Linux host support is in development, but is macos target 
 even possible/panned?

**Comment by fwcd** [comment]
> It seems like windows host support is planned and Linux host support is in development, but is macos target
even possible

Note that Windows host support != Windows target support, which (as per #11) might not be possible either. From what I understand, licensing restrictions would be the biggest issue, neither macOS nor Windows allow free redistribution of their frameworks and headers in the way that most Linux distributions do.

It might be technically possible to create a cross-compilation SDK that targets macOS by copying the corresponding frameworks and headers from a macOS installation yourself, but that likely won't be a supported scenario here.

**Comment by MaxDesiatov** [comment]
This is a legal question, not a technical question. Please refer to Xcode and macOS SDK license agreement for clarification.
